image: microsoft/dotnet:latest

stages:
  - build

variables:
  project: "DORS"

before_script:
  - "dotnet restore"

build:
  stage: build
  variables:
    build_path: "$project"
  script:
    - "ls"
    - "cd DORS"
    - "dotnet build"
    - "echo $project"
    - "echo $build_path"

test:
  stage: test
  variables:
    test_path: "$(project).Test.Integration"
  script:
    - "cd $test_path"
    - "dotnet test"